conditionally build jack backend

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,32 +1,39 @@
 #!/bin/sh
 
 die() {
-  printf "error: %s\n" "$1"
-  exit 1
+	printf "error: %s\n" "$1"
+	exit 1
 }
 
 check_pc() {
-  printf "checking for pkg-config..."
-  if command -v pkg-config >/dev/null; then
-    echo yes
-  else
-    echo no
-    die "pkg-config not found."
-  fi
+	printf "checking for pkg-config..."
+	if command -v pkg-config >/dev/null; then
+		echo yes
+	else
+		echo no
+		die "pkg-config not found."
+	fi
+}
+
+check_jack() {
+	printf "checking for jack..."
+	if pkg-config jack; then
+		echo "yes"
+		JACK_BINS="usporth_jack"
+		JACK_CFLAGS=$(pkg-config --cflags jack)
+		JACK_LDLIBS=$(pkg-config --libs jack)
+	else
+		echo "no"
+		echo "  jack backend will not be built."
+	fi
+	cat <<-EOF >> config.mk
+		JACK_CFLAGS=${JACK_CFLAGS}
+		JACK_LDLIBS=${JACK_LDLIBS}
+		JACK_BINS=${JACK_BINS}
+	EOF
 }
 
 check_pc
 
-printf "checking for jack..."
-if ! pkg-config jack; then
-  echo "no"
-  die "please make sure jack is installed."
-fi
-echo "yes"
-JACK_CFLAGS=$(pkg-config --cflags jack)
-JACK_LDLIBS=$(pkg-config --libs jack)
-
-cat <<EOF > config.mk
-JACK_CFLAGS=${JACK_CFLAGS}
-JACK_LDLIBS=${JACK_LDLIBS}
-EOF
+:> config.mk
+check_jack
